<?php
namespace backend\models;
use phpDocumentor\Reflection\Types\True_;

class AuthAssignment extends \common\models\AuthAssignment {
    public  function  getUsername(){
        return $this->hasOne(User::class, ['id' => 'user_id']);

    }

    public  function  attributeLabels()
    {
        return array_merge(parent::attributeLabels(),[
            'item_name' => 'Role',
            'user_id' => 'Username'
        ])
      //  return parent::attributeLabels(); // TODO: Change the autogenerated stub
//        return  [
//            'item_name' => 'Role',
//            'user_id' => 'Username',
//            'created_at' => 'Create_at'
//        ];
    }
}

?>